version: "3.1"

volumes:
  bosan-data:
  bosan-db:

services:
  proxy:
    image: nginx:1.17.8-alpine
    container_name: proxy.bosan
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./proxy:/etc/nginx:ro

  bosan-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server.bosan
    environment:
      DATABASE_URI: mongodb://db.bosan/bosan
      AUTH_SAMESITE: 'false'
      AUTH_SECURE: 'false'
    volumes:
      - ./server/src:/srv/app/src
      - bosan-data:/srv/data
    depends_on:
      - mongodb
      - proxy

  bosan-client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile.dev
    container_name: client-admin.bosan
    volumes:
      - ./client-admin/src:/srv/app/src
    depends_on:
      - proxy

  # bosan-client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   container_name: client.bosan
  #   volumes:
  #     - ./client/src:/srv/app/src
  #   depends_on:
  #     - proxy

  mongodb:
    image: mongo:4.2
    container_name: db.bosan
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bosan
    volumes:
      - bosan-db:/data/db
