name: Build Master

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - '.github/workflows/master-build-client.yml'

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build ./client --tag bosancz/bosan.cz-client
      - name: Login to DockerHub
        run: docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Push to DockerHub
        run: docker push bosancz/bosan.cz-client